language: android
branches:
  only:
    - master
    # We release from tags that follow semantic versioning:
    - /^v\d+\.\d+\.\d+(?:-rc\d+)?$/
android:
  components:
    - android-28
    - build-tools-29.0.2
    - tools
    - extra-android-m2repository
    - extra-google-m2repository
    - platform-tools
git:
  depth: 500
script:
  - ./gradlew build --stacktrace
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
deploy:
  - provider: script
    skip_cleanup: true
    script: ./release.sh
    on:
      repo: schibsted/account-sdk-android
      branch: publish-maven-central
