language: android
branches:
  only:
    - master
    # We release from tags that follow semantic versioning:
    - /^v\d+\.\d+\.\d+(?:-rc\d+)?$/
android:
  components:
    - android-28
    - build-tools-29.0.2
    - tools
    - extra-android-m2repository
    - extra-google-m2repository
    - platform-tools
git:
  depth: 500
before_install:
  - openssl aes-256-cbc -K $encrypted_de87219daf1c_key -iv $encrypted_de87219daf1c_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
before_script:
  # Since Gradle 5 we need extra memory for some tasks:
  - echo org.gradle.jvmargs=-Xmx2g > gradle.properties;
script:
  - ./gradlew build --stacktrace
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
deploy:
  - provider: script
    skip_cleanup: true
    script: ./release.sh
    on:
      tags: true
