-printusage
-keep class com.schibsted.account.common.util.*{ *; }
-keep class com.schibsted.account.common.tracking.*{ *; }
-keep class com.schibsted.account.common.smartlock.*{ *; }
-keep class com.schibsted.account.common.lib.*{ *; }